module.exports = {
  slider: require('~/model/ieltsviet/slider'),
  course: require('~/model/ieltsviet/course'),
  video: require('~/model/ieltsviet/video'),
  review: require('~/model/ieltsviet/review'),
  blog: require('~/model/ieltsviet/blog'),
  feedback: require('~/model/ieltsviet/feedback'),
  account: require('~/model/ieltsviet/account'),
  timekeeping: require('~/model/ieltsviet/timekeeping'),
  author: require('~/model/ieltsviet/author'),
  user: require('~/model/ieltsviet/user'),
  btest: require('~/model/ieltsviet/btest'),
  stest: require('~/model/ieltsviet/stest'),
  testpart: require('~/model/ieltsviet/testpart'),
  question: require('~/model/ieltsviet/question'),
  completepart: require('~/model/ieltsviet/completepart'),
  testcollection: require('~/model/ieltsviet/testcollection'),
};
